version: "3.8"
services: 
  web: 
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    image: app:code
    container_name: endpoint_container_3
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - .db.sqlite3:/var/lib/sqlite
    environment:
      - SQLITE3_DB=db.sqlite3